### ISSUE TITLE
01. 유사회사 Yachu 

### ISSUE THREAD

**Issue by ytbeom** [UnorganizedCompany/HyperGame#2]
### 개요
* 유사회사 컨텐츠 용으로 각자 만든 알고리즘으로 돌아가는 Yachu를 만들어보고자 함

### 구성
* 기존에 구상했던 계정 관리, 웹 같은 내용은 제외하고, 아주 간단하게 로컬에서 돌아가는 프로그램 정도로 구현
* 각자 만든 알고리즘 파일을 argument로 받아서 실행하는 단순한 방식
  * e.g., run.sh 2(player 수) tb.jar jb.py
* 화면 그리기 + 알고리즘 호출해서 결과값 받기 모두 한 프로그램에서 수행하는 구조로 생각 중
* 알고리즘 호출 시에는 현재 게임 상태를 argument로 전달
  * 그냥 string으로 전달할까 했는데 생각보다 전달할 내용이 많을 것 같아 json 파일을 매 trial마다 떨궈서 그걸 읽어가는 식이 나을 것 같음
```json
"state": {
  "turn": 7,
  "player": "tb",
  "trial": 1,
  "dices": [1, 2, 3, 4, 5],
  "scoreBoard": {
    "tb": {
      "aces": 2,
      "deuces": 2,
      "threes": 3,
      "fours": null,
      "fives": null,
      "sixes": 0,
      "choice": 12,
      "fourKind": null,
      "fullHouse": null,
      "smallStraight": null,
      "largeStraight": null,
      "yacht": 30
    },
    "jb": {
      "aces": 2,
      "deuces": 2,
      "threes": 3,
      "fours": null,
      "fives": null,
      "sixes": 0,
      "choice": 12,
      "fourKind": null,
      "fullHouse": null,
      "smallStraight": null,
      "largeStraight": null,
      "yacht": 30
    },
  }
}
``` 
* 알고리즘은 json 파일 경로를 받고, json 파일을 읽어서 의사결정 결과를 전달
  * 이것도 파일로 해도 되고, 아니면 이 정도는 string json으로 해서 게임 엔진에서 파싱해도 될듯?
```json
"decision" : {
  "keep": [0, 2, 4, 1],
  "choice": null
}
```
```json
"decision" : {
  "keep": [0, 2, 4, 1, 3],
  "choice": "largeStraight"
}
```

### 게임 화면
* 스위치 같은 화면은 바라지 않고, 스팀에 있는 화면 정도면 충분할 듯
* ![image](https://user-images.githubusercontent.com/6951003/152700845-9faab338-8953-4fc3-9aa2-646d3e64aef8.png)

### TO DO
* 게임 엔진 개발(1) - 심이 go로 짜주심
  * 알고리즘 호출
  * 파일 read, write
  * 게임 state 관리
* 게임 화면 개발(1) - 유가 KorGE로 도전
  * 스코어, ROLL, KEEP 버튼 등
* in-out 구체화(1) - 심&유
  * (엔진 - 알고리즘) json 파일 말고 다른 방식으로 데이터를 주고받을 수 있는 방법도 제시해주면 좋음, 더 필요한 필드 있을지 구체화하는 작업 필요, choice가 not null이면 현재 주사위를 바로 넣을거기 때문에 keep을 업데이트해서 주지 않아도 된다 같은 규칙도 정해서 공유
  * (엔진 - 화면) 결과물 내용물 정도만 공유되고, 그걸 화면에서 잘 이쁘게 그리는거만 하면 됨
* 테스트용 Algorithm 제작 - 최

**Comment by jbeomchoi** [comment]
### 테스트용 알고리즘

- Mybox 에 scala-library.jar 와 yacht-decision-runner-assembly.jar 를 업로드해둠.
- 웹서버로도, 파일 파싱으로도 가능하도록 함 (실행 시 옵션에 따라 실행. 이는 뒤에 설명)
- 로직은 간단함. 리롤은 없고(추후 추가 예정), 현재 점수를 기록할 수 있는 것 중에 주사위 조합으로 만들 수 있는 가장 높은 점수를 택하도록 함.
  - 모두 0점이라서 뭔가를 버려야 할 때는 json key 앞쪽에 있는 걸 우선적으로 하도록 함.
- 코드 위치 : https://github.com/UnorganizedCompany/yacht-decision

### 사용법

- 웹서버 실행
```sh
java -cp scala-library.jar:yacht-decision-runner-assembly.jar webserver --port {port}

## 예시 커맨드
java -cp /Users/user/env/scala/lib/scala-library.jar:/Users/user/private/pseudo_company/yacht-decision/yacht-decision-runner/target/scala-2.12/yacht-decision-runner-assembly.jar com.unorganized.example.Runner webserver --port 9910
```
  - 포트는 필수 arg 는 아니고 default 는 9902 로 설정되어 있음.

- 웹서버 요청 방법
```sh
curl -X POST -H "Content-Type: application/json" -d @{json file path} {host:port}/decide

## 예시 커맨드
curl -X POST -H "Content-Type: application/json" -d @./json/example.json http://localhost:9910/decide
```
- 결과는 아래와 같이 나옴
```json
{"decision":"yacht"}
```

- 아래와 같이 포스트맨으로 실행도 가능한데, 꼭 `Content-Type` 에 `application/json` 을 넣어줘야 함

<img width="434" alt="image" src="https://user-images.githubusercontent.com/65939592/153735750-7f0c0405-db21-4219-ac84-900db515cc20.png">

- 파일 파싱으로 실행
```sh
java -cp scala-library.jar:yacht-decision-runner-assembly.jar file --file-path {path_to_file}

## 예시 커맨드
java -cp /Users/user/env/scala/lib/scala-library.jar:/Users/user/private/pseudo_company/yacht-decision/yacht-decision-runner/target/scala-2.12/yacht-decision-runner-assembly.jar com.unorganized.example.Runner file --file-path ./json/example.json
```
  - `file-path` 옵션은 필수로 들어가야 하고 안 넣어주면 실행되지 않음.
  - 현재는 그냥 표준출력으로 해두었는데 필요시에는 파일로 쓰기도 가능. 이건 엔진 쪽에서 해달라는 대로 해줌

- 파일 실행 결과 예시
```sh
List((yacht,50), (fives,25))
yacht
```
- 위의 List 는 현재 기록이 가능한 예시를 보여주기 위함이고(디버깅용. 삭제 요청 시 삭제해드림) 아래는 어떤 점수를 기록할 지가 나옴.

- 수정사항 요청하면 반영하겠음

**Comment by jaemoon-sim** [comment]
## 409 conflict

@jbeomchoi 

```json
{
 "turn": 1,
 "player": "0",
 "trial": 1,
 "dices": [
  4,
  5,
  5,
  6,
  6
 ],
 "scoreBoard": {
  "0": {
   "ones": null,
   "twos": null,
   "threes": null,
   "fours": null,
   "fives": null,
   "sixs": null,
   "choice": null,
   "four_of_a_kind": null,
   "full_house": null,
   "small_straight": null,
   "large_straight": null,
   "yacht": null
  },
  "1": {
   "ones": null,
   "twos": null,
   "threes": null,
   "fours": null,
   "fives": null,
   "sixs": null,
   "choice": null,
   "four_of_a_kind": null,
   "full_house": null,
   "small_straight": null,
   "large_straight": null,
   "yacht": null
  }
 }
}
```

에러 로그
```
[armeria-common-worker-nio-2-2] WARN com.unorganized.example.RestExceptionHandler - Exception occur.
org.json4s.MappingException: Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:56)
	at org.json4s.Extraction$.$anonfun$convert$2(Extraction.scala:882)
	at scala.Option.getOrElse(Option.scala:189)
	at org.json4s.Extraction$.convert(Extraction.scala:882)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:457)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:781)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:257)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:781)
	at org.json4s.Extraction$.extract(Extraction.scala:455)
	at org.json4s.Extraction$.extract(Extraction.scala:56)
	at org.json4s.ExtractableJsonAstNode$.extract$extension(ExtractableJsonAstNode.scala:22)
	at com.unorganized.example.Decider$.decide(Decider.scala:34)
	at com.unorganized.example.DecisionService.parseModooCuveDocument(DecisionService.scala:25)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:394)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$8(AnnotatedService.java:362)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:291)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:283)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:420)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:363)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:319)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:305)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:427)
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:255)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:517)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
[armeria-common-worker-nio-2-2] INFO com.linecorp.armeria.logging.access - 0:0:0:0:0:0:0:1 - - 13/Feb/2022:18:28:49 +0900 "POST /decide#DecisionService/parseModooCuveDocument h1c" 409 12
[armeria-common-worker-nio-2-4] WARN com.unorganized.example.RestExceptionHandler - Exception occur.
org.json4s.MappingException: Did not find value which can be converted into java.lang.String
	at org.json4s.reflect.package$.fail(package.scala:56)
	at org.json4s.Extraction$.$anonfun$convert$2(Extraction.scala:882)
	at scala.Option.getOrElse(Option.scala:189)
	at org.json4s.Extraction$.convert(Extraction.scala:882)
	at org.json4s.Extraction$.$anonfun$extract$10(Extraction.scala:457)
	at org.json4s.Extraction$.$anonfun$customOrElse$1(Extraction.scala:781)
	at scala.PartialFunction.applyOrElse(PartialFunction.scala:127)
	at scala.PartialFunction.applyOrElse$(PartialFunction.scala:126)
	at scala.PartialFunction$$anon$1.applyOrElse(PartialFunction.scala:257)
	at org.json4s.Extraction$.customOrElse(Extraction.scala:781)
	at org.json4s.Extraction$.extract(Extraction.scala:455)
	at org.json4s.Extraction$.extract(Extraction.scala:56)
	at org.json4s.ExtractableJsonAstNode$.extract$extension(ExtractableJsonAstNode.scala:22)
	at com.unorganized.example.Decider$.decide(Decider.scala:34)
	at com.unorganized.example.DecisionService.parseModooCuveDocument(DecisionService.scala:25)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:394)
	at com.linecorp.armeria.internal.server.annotation.AnnotatedService.lambda$serve0$8(AnnotatedService.java:362)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.doComplete(UnmodifiableFuture.java:124)
	at com.linecorp.armeria.common.util.UnmodifiableFuture.lambda$wrap$0(UnmodifiableFuture.java:100)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at com.linecorp.armeria.common.stream.StreamMessageCollector.onComplete(StreamMessageCollector.java:67)
	at com.linecorp.armeria.common.stream.AbstractStreamMessage$CloseEvent.notifySubscriber(AbstractStreamMessage.java:257)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent0(DefaultStreamMessage.java:291)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriberOfCloseEvent(DefaultStreamMessage.java:283)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.handleCloseEvent(DefaultStreamMessage.java:420)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber0(DefaultStreamMessage.java:363)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.notifySubscriber(DefaultStreamMessage.java:319)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.addObjectOrEvent(DefaultStreamMessage.java:305)
	at com.linecorp.armeria.common.stream.DefaultStreamMessage.close(DefaultStreamMessage.java:427)
	at com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:216)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:255)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:517)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by jaemoon-sim** [comment]
## yachtengine v0 배포
- mybox에 `yachtengine.zip` 파일을 업로드해두었습니다.
- 압축해제하면 실행파일 `yachtengine` 파일이 들어있읍니다. (intel 맥 용으로 컴파일 되어있음)
- https://github.com/jaemoon-sim/HyperGame/tree/main/YachtEngine#readme 를 참고하시어 커맨드라인에서 실행시키시면 됩니다.

**Comment by ytbeom** [comment]
@jaemoon-sim 님, readme 보고 코멘트가 있습니다.
1. decision을 한 경우에는 keep이 0, 1, 2, 3, 4로 고정되어 들어오는 식으로 되어있는게 맞을까요?
2. log에 player를 추가해주실 수 있을까요? string list 형태로 추가해주시면 참 좋을 것으로 사료됩니다.
3. final은 제가 미처 생각하지 못했는데 꼼꼼히 챙겨주셔서 감사합니다.

**Comment by jaemoon-sim** [comment]
@ytbeom 

> 1. decision을 한 경우에는 keep이 0, 1, 2, 3, 4로 고정되어 들어오는 식으로 되어있는게 맞을까요?

사실 구현상으로는, **`choice`가 비어있지 않으면 decision을 했다**고 처리하고 있습니다. `keep`대신에 `choice` 필드를 봐주세요

> 2. log에 player를 추가해주실 수 있을까요? string list 형태로 추가해주시면 참 좋을 것으로 사료됩니다.

넵

> 3. final은 제가 미처 생각하지 못했는데 꼼꼼히 챙겨주셔서 감사합니다.

🔥

**Comment by jaemoon-sim** [comment]
@ytbeom 수정하여 push도 해뒀고, MyBox에 yachtengine_0218_00.zip 으로 배포해두었습니다 👍

**Comment by ytbeom** [comment]
## YachtKorge
* https://github.com/ytbeom/HyperGame
* Readme가 HyperGame 거라서 아직 수정은 안되었읍니다
* 빌드하는 방법 등을 정리해서 올려두도록 하겠읍니다

**Comment by jbeomchoi** [comment]
### Yacht 룰

![image](https://user-images.githubusercontent.com/65939592/156570034-bb26daaa-f5f7-4901-8c47-9e773d71a01c.png)

기본적으로 점수 계산은 상단 이미지를 따름 (ref: https://namu.wiki/w/%EC%9A%94%ED%8A%B8(%EA%B2%8C%EC%9E%84)?from=%EC%95%BC%EC%B6%94#s-2.2)

![image](https://user-images.githubusercontent.com/65939592/156569824-6aefbcb8-6ded-44c0-a9f0-39b10bde5dc1.png)

보너스는 63 이상일 때 +35점

- 점수판 기록이 되고 나면 그 점수판은 사용 불가
- 점수판 0 점 기록은 자유, 나머지의 경우에는 족보에 맞아야 해당하는 점수 기록 가능
- 여러 족보에 맞는 경우가 있을 수 있고, 그 경우에는 선택해서 기록(가장 높은 점수를 기록하지 않아도 됨)

**Comment by jaemoon-sim** [comment]
yachtengine_0306_00.zip 업데이트 되었읍니다
1) keep dice 버그 수정
2) trial = 3일 때 choice 없으면 실패하도록 처리
3) 플레이어 실수로 게임이 멈추면, 반칙패 하도록 추가

https://github.com/jaemoon-sim/HyperGame/blob/main/YachtEngine/README.md

**Comment by ytbeom** [comment]
@jaemoon-sim 님,
버그로 보이는 현상이 있어 제보드립니다.
```json
{
"state": {
    "turn": 2,
    "player": "tb",
    "trial": 3,
    "dices": [
     4,
     3,
     6,
     4,
     5
    ],
    "scoreBoard": {
     "hk": {
      "aces": null,
      "deuces": 6,
      "threes": null,
      "fours": null,
      "fives": null,
      "sixes": null,
      "subtotal": 6,
      "choice": null,
      "fourKind": null,
      "fullHouse": null,
      "smallStraight": null,
      "largeStraight": null,
      "yacht": null,
      "total": 6
     },
     "tb": {
      "aces": null,
      "deuces": null,
      "threes": null,
      "fours": null,
      "fives": null,
      "sixes": null,
      "subtotal": 0,
      "choice": null,
      "fourKind": null,
      "fullHouse": 23,
      "smallStraight": null,
      "largeStraight": null,
      "yacht": null,
      "total": 23
     }
    }
   },
   "decision": {
    "keep": [],
    "choice": "smallStraight"
   }
}
```
이렇게 넣었는데 smallStraight에 0점이 들어갔어요ㅠㅠ

**Comment by jbeomchoi** [comment]
그냥 여기서 보는 게 편하실 거 같아서... 올립니다

파일 위치 : `공유폴더 > 유사회사 > 야추 파일 공유용 > 알고리즘_정범`

다운받아야 하는 파일 : `scala-library.jar`, `yacht-decision-runner-assembly-v1.jar`

실행 커맨드 ( 꼭 **cmd 창**에서 실행 )

```sh
java -cp scala-library.jar;yacht-decision-runner-assembly-v1.jar com.unorganized.example.Runner webserver --port {포트번호}
```
